### ISSUE TITLE
NPE in gslator

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#100]
### Expected Behavior

no exceptions

### Actual Behavior

```
java.lang.NullPointerException
	at com.cevelop.gslator.checkers.visitors.ES40ToES64ExpressionRules.ES49IfMustUseNamedCastVisitor.visit(ES49IfMustUseNamedCastVisitor.java:33)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTBinaryExpression.accept(CPPASTBinaryExpression.java:164)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTStaticAssertionDeclaration.accept(CPPASTStaticAssertionDeclaration.java:86)
	at org.eclipse.cdt.internal.core.dom.parser.ASTTranslationUnit.accept(ASTTranslationUnit.java:289)
	at com.cevelop.gslator.checkers.ES40ToES64ExpressionRules.ES49IfMustUseNamedCastChecker.checkAst(ES49IfMustUseNamedCastChecker.java:24)
	at com.cevelop.gslator.checkers.BaseChecker.processAst(BaseChecker.java:115)
	at ch.hsr.ifs.iltis.cpp.core.wrappers.AbstractIndexAstChecker.processModel(AbstractIndexAstChecker.java:117)
	at org.eclipse.cdt.codan.internal.core.CodanRunner.processResource(CodanRunner.java:95)
	at org.eclipse.cdt.codan.internal.core.CodanRunner.runInEditor(CodanRunner.java:50)
	at org.eclipse.cdt.codan.internal.core.CodanBuilder.processResource(CodanBuilder.java:130)
	at org.eclipse.cdt.codan.core.cxx.internal.model.CxxCodanReconciler.reconciledAst(CxxCodanReconciler.java:40)
	at org.eclipse.cdt.codan.internal.ui.cxx.CodanCReconciler.reconciled(CodanCReconciler.java:60)
	at org.eclipse.cdt.internal.ui.editor.CEditor.reconciled(CEditor.java:3134)
	at org.eclipse.cdt.internal.ui.text.CReconcilingStrategy.reconcile(CReconcilingStrategy.java:100)
	at org.eclipse.cdt.internal.ui.text.CReconcilingStrategy.reconcile(CReconcilingStrategy.java:64)
	at org.eclipse.cdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:89)
	at org.eclipse.cdt.internal.ui.text.CCompositeReconcilingStrategy.reconcile(CCompositeReconcilingStrategy.java:90)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:76)
	at org.eclipse.cdt.internal.ui.text.CReconciler.process(CReconciler.java:351)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:210)
```

### Cevelop Version, Operating System and Compiler

Cevelop C++ IDE

Version: 1.12.0-201906270918

macos mojave

could be an error following the many arrayexceptions I got from parsing.

**Comment by PeterSommerlad** [comment]
seems no longer to appear...
