### ISSUE TITLE
Arraystore exception (mit stacktrace)

### ISSUE THREAD

**Issue by PeterSommerlad** [Cevelop/Issues#102]
### Expected Behavior

no exceptions while indexing, index complete. (note code parsed uses C++17 structured bindings)

### Actual Behavior

```
java.lang.ArrayStoreException: org.eclipse.cdt.internal.core.dom.parser.cpp.CPPClassSpecialization$RecursionResolvingMethod
	at org.eclipse.cdt.internal.core.dom.parser.cpp.AbstractCPPClassSpecializationScope.specializeMembers(AbstractCPPClassSpecializationScope.java:226)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.AbstractCPPClassSpecializationScope.getConstructors(AbstractCPPClassSpecializationScope.java:257)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPClassSpecialization.getConstructors(CPPClassSpecialization.java:290)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.EvalTypeId.computeConstructor(EvalTypeId.java:302)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.EvalTypeId.getConstructor(EvalTypeId.java:281)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.EvalTypeId.instantiate(EvalTypeId.java:431)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.EvalUnary.instantiate(EvalUnary.java:397)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPTemplates.instantiateType(CPPTemplates.java:1564)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPTemplates.createSpecialization(CPPTemplates.java:1068)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPClassSpecialization.specializeMember(CPPClassSpecialization.java:196)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.AbstractCPPClassSpecializationScope.specializeMembers(AbstractCPPClassSpecializationScope.java:225)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.AbstractCPPClassSpecializationScope.getConstructors(AbstractCPPClassSpecializationScope.java:257)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPClassSpecialization.getConstructors(CPPClassSpecialization.java:290)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPSemantics.findImplicitlyCalledConstructor(CPPSemantics.java:3806)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPSemantics.findImplicitlyCalledConstructor(CPPSemantics.java:3776)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPSemantics.findImplicitlyCalledConstructor(CPPSemantics.java:3699)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.semantics.CPPSemantics.findImplicitlyCalledConstructor(CPPSemantics.java:3674)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTConstructorChainInitializer.getImplicitNames(CPPASTConstructorChainInitializer.java:249)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTConstructorChainInitializer.accept(CPPASTConstructorChainInitializer.java:124)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTFunctionDefinition.accept(CPPASTFunctionDefinition.java:213)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTCompositeTypeSpecifier.accept(CPPASTCompositeTypeSpecifier.java:201)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTSimpleDeclaration.accept(CPPASTSimpleDeclaration.java:108)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTNamespaceDefinition.accept(CPPASTNamespaceDefinition.java:144)
	at org.eclipse.cdt.internal.core.dom.parser.ASTTranslationUnit.accept(ASTTranslationUnit.java:289)
	at org.eclipse.cdt.internal.core.pdom.PDOMWriter.process(PDOMWriter.java:544)
	at org.eclipse.cdt.internal.core.pdom.AbstractIndexerTask.writeToIndex(AbstractIndexerTask.java:1290)
	at org.eclipse.cdt.internal.core.pdom.AbstractIndexerTask.parseFile(AbstractIndexerTask.java:1107)
	at org.eclipse.cdt.internal.core.pdom.AbstractIndexerTask.parseLinkage(AbstractIndexerTask.java:910)
	at org.eclipse.cdt.internal.core.pdom.AbstractIndexerTask.runTask(AbstractIndexerTask.java:572)
	at org.eclipse.cdt.internal.core.pdom.indexer.PDOMIndexerTask.run(PDOMIndexerTask.java:164)
	at org.eclipse.cdt.internal.core.pdom.indexer.PDOMRebuildTask.run(PDOMRebuildTask.java:94)
	at org.eclipse.cdt.internal.core.pdom.PDOMIndexerJob.run(PDOMIndexerJob.java:160)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### Cevelop Version, Operating System and Compiler

The more we know about your setup, the easier it will be for us to reproduce the problem.

eclipse.buildId=unknown
java.version=9.0.4
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_CH
Framework arguments:  -keyring /Users/sop/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/sop/.eclipse_keyring

Cevelop C++ IDE

Version: 1.12.0-201906270918

**Comment by PeterSommerlad** [comment]
source wo es passiert:https://github.com/PeterSommerlad/Psst

**Comment by PeterSommerlad** [comment]
no longer happens with Cevelop 1.12.1
