### ISSUE TITLE
Linticator won't run

### ISSUE THREAD

**Issue by DdOtzen** [Cevelop/Issues#128]
It is a bit unclear, but linicator repo does not have a issue tab, so I assume here is the place to post linticator issues too?

### Expected Behavior

When i click "run linicator" i expect it to run some lint commands.
And if it can't, I expect an error message that enables me to identify the problem.

### Actual Behavior

I get a pop-up saying 
` (Cannot create a file when that file already exists)`

I have no clue what that file is.
the log does not tell me eiter
```

!ENTRY com.linticator.Linticator 4 0 2022-02-01 13:14:43.242
!MESSAGE  (Cannot create a file when that file already exists)
!STACK 0
java.io.FileNotFoundException:  (Cannot create a file when that file already exists)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at com.linticator.base.FileUtil.readFile(FileUtil.java:22)
	at com.linticator.config.CompilerConfigConfigurator.updateCompilerConfigFile(CompilerConfigConfigurator.java:31)
	at com.linticator.config.ProjectConfig.updateConfig(ProjectConfig.java:143)
	at com.linticator.lint.LintProjectJob.runLint(LintProjectJob.java:41)
	at com.linticator.lint.LintJob.run(LintJob.java:84)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### Cevelop Version, Operating System and Compiler
Well no cevelop version.
It is 
Code Composer Studio  Version: 11.1.0.00011 
Based on
Eclipse Version: 2.3.500.v20210303-1800 Build id: I20210303-1800
with
Linticator	1.6.0.202105261547

**Comment by DdOtzen** [comment]
Update: I discovered that linticator somehow lost is't setup.
after instalation i configured it, and ran the provoded test, all fine, i ran it on my code, all fine.
Then I experienced that a run of linticator resultet in a lot of entries in progress window of "remote system operation" and a message that heap mem was running low, where after eclipse grinded to a halt.
I had to force close it.
It was after this force close i saw the behaviour described in issue.
Later i remembered to the build in test, and it was here i got a message that linticator was not configured, i ran the configuration once more and the issue disappeared.

So it is fixed for me, but I leave it open, for you to cosider if it is possible to give better error message in this case (if reproducible)
