### ISSUE TITLE
Templator Bug in Cevelop 1.7

### ISSUE THREAD

**Issue by tonisuter** [Cevelop/Issues#19]
The Templator plug-in seems to be broken in Cevelop 1.7 (at least on macOS). Even for trivial examples the following exception is thrown:

```
java.lang.NoSuchMethodError: org.eclipse.cdt.internal.core.dom.rewrite.changegenerator.ChangeGeneratorWriterVisitor.<init>(Lorg/eclipse/cdt/internal/core/dom/rewrite/ASTModificationStore;Ljava/lang/String;Lorg/eclipse/cdt/internal/core/dom/rewrite/commenthandler/NodeCommentMap;)V
	at com.cevelop.templator.plugin.viewdata.FindNodeRegionsVisitor.<init>(FindNodeRegionsVisitor.java:26)
	at com.cevelop.templator.plugin.viewdata.ASTWriterRegionFinder.<init>(ASTWriterRegionFinder.java:25)
	at com.cevelop.templator.plugin.viewdata.ViewData.prepareForView(ViewData.java:45)
	at com.cevelop.templator.plugin.view.tree.TreeEntry.loadOperation(TreeEntry.java:38)
	at com.cevelop.templator.plugin.view.components.AsyncEntryLoader$1.run(AsyncEntryLoader.java:38)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

This bug doesn't occur in Cevelop 1.6 as far as I can tell.

**Comment by tcorbat** [comment]
Confirmed. This is an issue with the const placement patch, as Templator uses internal CDT API that has changed.

**Comment by tcorbat** [comment]
The reason for this issue origins in the modifications to internal API of CDT that Templator relies on. We will remove the const placement feature that contains this change for 1.7.1. It will be back in 1.8.0.
