### ISSUE TITLE
NPE during "Organize Includes

### ISSUE THREAD

**Issue by fmorgner** [Cevelop/Issues#22]
The problem described in this issue was first reported by @rtosman in #17.

### Expected Behavior

Running "Organize Include" on a project should provide a list of suggested actions.

### Actual Behavior

Running "Organize Includes" results in a NullPointerException being thrown during analysis.

### Cevelop Version, Operating System and Compiler

1.7.0, All OS, All Compilers

### Steps to reproduce:

1. Create a new C++ project in Cevelop
2. Add the following two files (They have to be two separate files!):

    - GH17ClassNPE.h:
    ```c++
    #ifndef GH17_CLASS_NPE
    #define GH17_CLASS_NPE
    
    class GH17ClassNPE: public GH17ClassNPEBase { // The base must not exist!
	    GH17ClassNPE();
    };
    #endif
    ```

    - GH17ClassNPE.cpp:
    ```c++
    #include "GH17ClassNPE.h"
    
    GH17ClassNPE::GH17ClassNPE() : GH17ClassNPEBase { } {
    }
    ```

3. Run Includator "Organize Includes" on either the Project or the CPP file (This is important since running it on the header will not produce the NPE)

### Stacktrace:
```
java.lang.NullPointerException
	at com.cevelop.includator.helpers.ConstructorReferenceHelper.findImplicitlyInitializedBaseClasses(ConstructorReferenceHelper.java:78)
	at com.cevelop.includator.helpers.ConstructorReferenceHelper.addImplicitBaseClassConstructors(ConstructorReferenceHelper.java:49)
	at com.cevelop.includator.helpers.DeclarationReferenceVisitor.performAdditionalRefActions(DeclarationReferenceVisitor.java:213)
	at com.cevelop.includator.helpers.DeclarationReferenceVisitor.addName(DeclarationReferenceVisitor.java:159)
	at com.cevelop.includator.helpers.DeclarationReferenceVisitor.visit(DeclarationReferenceVisitor.java:81)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTName.accept(CPPASTName.java:150)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTQualifiedName.accept(CPPASTQualifiedName.java:247)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTDeclarator.accept(CPPASTDeclarator.java:190)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTFunctionDefinition.accept(CPPASTFunctionDefinition.java:204)
	at org.eclipse.cdt.internal.core.dom.parser.ASTTranslationUnit.accept(ASTTranslationUnit.java:266)
	at com.cevelop.includator.helpers.DeclarationReferenceHelper.findDeclReferences(DeclarationReferenceHelper.java:54)
	at com.cevelop.includator.resources.IncludatorFile.getDeclarationReferences(IncludatorFile.java:60)
	at com.cevelop.includator.optimizer.findunusedincludes.FindUnusedIncludesAlgorithm.run(FindUnusedIncludesAlgorithm.java:55)
	at com.cevelop.includator.optimizer.Algorithm.start(Algorithm.java:42)
	at com.cevelop.includator.optimizer.ScopedAlgorithm.run(ScopedAlgorithm.java:34)
	at com.cevelop.includator.optimizer.Algorithm.start(Algorithm.java:42)
	at com.cevelop.includator.optimizer.Optimizer.run(Optimizer.java:37)
	at com.cevelop.includator.ui.OptimizationRunner.run(OptimizationRunner.java:57)
	at com.cevelop.includator.ui.actions.IncludatorAlgorithmAction.runAnalysisJob(IncludatorAlgorithmAction.java:110)
	at com.cevelop.includator.ui.actions.IncludatorAlgorithmAction$1.runWithWorkbenchWindow(IncludatorAlgorithmAction.java:58)
	at com.cevelop.includator.ui.actions.IncludatorJob.run(IncludatorJob.java:32)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

### Notes

A similar NPE happens in relation to non-static member functions, but I am currently no able to reproduce it using a minimal example. For both of them, I have a preliminary fix on my own branch but further analysis is required to make sure that those are the only two situations causing NPEs.

**Comment by PeterSommerlad** [comment]
Would a workaround to rely on compilable code help?

**Comment by fmorgner** [comment]
Not sure since the code per se might be compilable, but if Cevelop is not aware of all include paths (e.g when importing a Makefile project) Includator will still raise an NPE.

**Comment by fmorgner** [comment]
Fixed in HEAD
