### ISSUE TITLE
NullPointerException while updating index for Includator

### ISSUE THREAD

**Issue by Bu11etmagnet** [Cevelop/Issues#88]
### Expected Behavior

I expected Includator to organize includes.

### Actual Behavior

NullPointerException with the follwing stack trace (seems to be different from #22)

eclipse.buildId=unknown
java.version=10.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

This is a continuation of log file .bak_4.log
Created Time: 2019-02-08 14:25:35.567

com.cevelop.includator
Error
Fri Feb 08 15:52:39 CET 2019
Error while performing static analysis.

java.lang.NullPointerException
	at com.cevelop.includator.optimizer.findunusedincludes.FindUnusedIncludesAlgorithm.addPaths(FindUnusedIncludesAlgorithm.java:181)
	at com.cevelop.includator.optimizer.findunusedincludes.FindUnusedIncludesAlgorithm.initAllPaths(FindUnusedIncludesAlgorithm.java:174)
	at com.cevelop.includator.optimizer.findunusedincludes.FindUnusedIncludesAlgorithm.run(FindUnusedIncludesAlgorithm.java:57)
	at com.cevelop.includator.optimizer.Algorithm.start(Algorithm.java:41)
	at com.cevelop.includator.optimizer.Optimizer.run(Optimizer.java:39)
	at com.cevelop.includator.ui.OptimizationRunner.run(OptimizationRunner.java:59)
	at com.cevelop.includator.ui.actions.IncludatorAlgorithmAction.runAnalysisJob(IncludatorAlgorithmAction.java:111)
	at com.cevelop.includator.ui.actions.IncludatorAlgorithmAction$1.runWithWorkbenchWindow(IncludatorAlgorithmAction.java:60)
	at com.cevelop.includator.ui.actions.IncludatorJob.run(IncludatorJob.java:33)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

### Cevelop Version, Operating System and Compiler

Cevelop C++ IDE
Version: 1.10.1-201809130520

OS: Linux, v.4.15.0-45-generic, x86_64 / gtk 2.24.32
Java version: 10.0.2

**Comment by Darnor** [comment]
Can you provide us with a code example where this happens?

**Comment by Bu11etmagnet** [comment]
Alas, I can't. It's proprietary code from work, and I don't remember which source file it was.
